#:kivy 2.0.0

<CasillaTablero@ButtonBehavior+FloatLayout>:
    ruta_fondo: ''
    color_tinte: 1, 1, 1, 1  # Filtro de color para manipular la imagen

    Image:
        source: root.ruta_fondo
        color: root.color_tinte
        allow_stretch: True
        keep_ratio: False
        size_hint: 1, 1
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

    Image:
        id: img_pieza
        source: ''
        allow_stretch: True
        keep_ratio: True
        size_hint: 0.85, 0.85
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

<VistaJuego@BoxLayout>:
    orientation: 'vertical'
    padding: dp(15)
    spacing: dp(10)
    canvas.before:
        Color:
            rgba: 0.1, 0.22, 0.29, 1  # Fondo azul calmado
        Rectangle:
            pos: self.pos
            size: self.size

    Label:
        id: lbl_titulo
        text: 'SALA DE MANDO'
        font_size: '28sp'
        bold: True
        size_hint_y: 0.15
        color: 0, 0.9, 0.78, 1

    AnchorLayout:
        size_hint_y: 0.6
        GridLayout:
            id: grid_tablero
            cols: 8
            rows: 8
            size_hint: None, None
            # Forzamos que sea un cuadrado perfecto basado en el ancho del móvil
            width: root.width - dp(30)
            height: root.width - dp(30)

    BoxLayout:
        orientation: 'vertical'
        size_hint_y: 0.25
        Label:
            id: lbl_estado
            text: 'Esperando despliegue...'
            font_size: '22sp'
            bold: True
            color: 0.96, 0.96, 0.98, 1
        Label:
            id: lbl_info
            text: 'Nivel: --'
            font_size: '18sp'
            color: 0.6, 0.7, 0.8, 1